### ISSUE TITLE
Permissions on `resolv.conf` restricted user access

### ISSUE THREAD

**Issue by gbraad** [containers/podman-wsl-fedora#3]
Since the use of F36, the container base uses the following permissions on `resolv.conf`:

```
[root@WinT14 ~]# ls -al /etc/resolv.conf
-rwx------ 1 root root 198 Jul 14 13:19 /etc/resolv.conf
```

this means that a new user is unable to use the DNS resolver:

```
[root@WinT14 gbraad]# su - core
[core@WinT14 ~]$ curl google.com
curl: (6) Could not resolve host: google.com
```

This could be fixed by setting:

```
[root@WinT14 gbraad]# chmod 644 /etc/resolv.conf
```

This is not a direct issue for our usecase, but would prevent people who want to use a non-root user inside the WSL environment.

Suggested to make this part of the image for now.

**Comment by gbraad** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2106999

**Comment by gbraad** [comment]
@n1hility I saw some changes you made to fix this, but it seems there is now an issue with successive builds ?

Workaround in: https://github.com/containers/podman-wsl-fedora/pull/6

**Comment by n1hility** [comment]
@n1hility yes will fix in a sec

**Comment by gbraad** [comment]
Upstream didn't reply as of yet. They changed behaviour that is not directly obvious. Will probably reach out to some of the other base maintainers. They used to include a prepopulated file, with entries from NetworkManager. While not correct for the container, this did create a file with the correct permissions. Since F36 they seem to have dropped with file, but I was unable to track where this change happened. The bootstrap files on Pagure of Fedora do not have this change.

**Comment by gbraad** [comment]
root cause is that anaconda has been changed: https://github.com/rhinstaller/anaconda/pull/3818

**Comment by gbraad** [comment]
Filed a PR at pagure for this: https://pagure.io/fedora-kickstarts/pull-request/898

**Comment by dustymabe** [comment]
I would argue that this is potentially an issue with the container runtime. For example.. Why does `podman` not have the same issue?

```
$ podman run -it --rm registry.fedoraproject.org/fedora:36 bash 
[root@d87d7bfb8951 /]# ls -l /etc/resolv.conf 
-rw-r--r--. 1 root root 45 Jul 20 17:42 /etc/resolv.conf
```

I think the goal by removing the `/etc/resolv.conf` from anaconda in https://github.com/rhinstaller/anaconda/pull/3818 is to toss the management of it to something else, which arguably is the right thing to do.

**Comment by n1hility** [comment]
@dustymabe it's not an issue for podman since it bind mounts over whatever would be in the image. The WSL issue occurs since they truncate and overwrite preserving the bad perms.  I agree it should be fine for fedora not to include it. The underlying issue seems to be the interaction of the container runtime and the podman export process for example:

```
$ podman run --name ftry -it fedora:36 bash
[root@02476962449d /]# ls -l /etc/resolv.conf 
-rw-r--r--. 1 root root 25 Jul 20 20:18 /etc/resolv.conf
[root@02476962449d /]# 
exit
$ podman export ftry -o ftry.tar
$ tar -tvf ftry.tar | grep resolv.conf
-rwx------  0 root   root        0 Jul 20 15:18 etc/resolv.conf
```

I believe what's happening here is that when the bind mount for resolv.conf is created by crun, the location is first touched with 700 perms, which when exported (either live or post shutdown) the file is present leading to the problem.

Note this doesn't happen if you disable the resolv.conf bind:

```
$ podman run --name ftry --dns none -it fedora:36 bash
[root@6e99489d2188 /]# ls -l /etc/resolv.conf
ls: cannot access '/etc/resolv.conf': No such file or directory
[root@6e99489d2188 /]# 
exit
$ podman export ftry -o ftry.tar
$ tar -tvf ftry.tar | grep resolv.conf
$ echo $?
1
```

Also runc appears to use a different umask, so works in this case:

```
$ podman --runtime=runc run --name ftry -it fedora:36 sh
sh-5.1# ls -l /etc/resolv.conf 
-rw-r--r--. 1 root root 25 Jul 20 20:49 /etc/resolv.conf
sh-5.1# 
exit
$ podman export ftry -o f.tar
$ tar -tvf f.tar  | grep resolv.conf
-rwxr-xr-x root/root         0 2022-07-20 15:49 etc/resolv.conf
```

Not sure if we should propose a change to crun or just accept it as a known issue.

**Comment by gbraad** [comment]
> Not sure if we should propose a change to crun or just accept it as a known issue.

The known issue is something that would have to be documented for the use of Fedora as a non-root container image. I think the majority of people will not realize what is happening.

**Comment by dustymabe** [comment]
> @dustymabe it's not an issue for podman since it bind mounts over whatever would be in the image. The WSL issue occurs since they truncate and overwrite preserving the bad perms. I agree it should be fine for fedora not to include it. The underlying issue seems to be the interaction of the container runtime and the podman export process for example:

There are a lot of small details here that I'm missing. Is WSL just taking the Fedora container image directly and using it? If that's the case then how does "truncate and overwrite preserving the bad perms" happen because the file doesn't exist at all right?

From your comments it seems like maybe we massage the image before handing it to WSL?

Find me on IRC (i'm in `#podman`) if you'd like to talk more.

**Comment by n1hility** [comment]
> > @dustymabe it's not an issue for podman since it bind mounts over whatever would be in the image. The WSL issue occurs since they truncate and overwrite preserving the bad perms. I agree it should be fine for fedora not to include it. The underlying issue seems to be the interaction of the container runtime and the podman export process for example:
> 
> There are a lot of small details here that I'm missing. Is WSL just taking the Fedora container image directly and using it? If that's the case then how does "truncate and overwrite preserving the bad perms" happen because the file doesn't exist at all right?
> 
> From your comments it seems like maybe we massage the image before handing it to WSL?

That's right, we run the image in podman to add packages and export a new rootfs tar, which WSL needs for imports.([workflow is here if you are curious](https://github.com/containers/podman-wsl-fedora/blob/main/.github/workflows/build-image.yml)). Since the file doesn't exist in the image, the act of running it in a container leads to the creation of the empty resolv.conf to bind mount a proper network config. When we get to the export at the end the resolv.conf with bad perms ends up included in the resulting rootfs tar.

To workaround we edit the tar and delete the entry, and add in an empty placeholder with standard perms just in case.

> Find me on IRC (i'm in `#podman`) if you'd like to talk more.

Sure will do.

**Comment by dustymabe** [comment]
Right. I'm thinking we should revert the https://pagure.io/fedora-kickstarts/pull-request/898 PR and file a bug against podman (assuming there is one) and in the short term fixup the permissions on this file in your tooling that creates the WSL image.

**Comment by cverna** [comment]
+1 to revert the kickstart hackery once this is fixed elsewhere, in the meantime if this is helping to have WSL working I would be fine leaving the hack in place.
Note the change was only made in rawhide so far, @gbraad where you able to test the rawhide image to make sure we the kickstart change worked?

**Comment by gbraad** [comment]
Not yet. Will do so asap.
Is the rawhide container published in the fp.o registry?

**Comment by gbraad** [comment]
We have fixed the WSL toolchain by adding a workaround.
I'll  also file an issue against gitpod

**Comment by cverna** [comment]
> Not yet. Will do so asap. Is the rawhide container published in the fp.o registry?

yes and quay.io using the rawhide tag

`podman pull quay.io/fedora/fedora:rawhide`
